services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --proxy-headers
    ports:
      - "8080:8080"
    environment:
      - TROCR_ENABLED=true
      - TROCR_RUN_DIR=/app/runs/default
      - TROCR_WEIGHTS_FILE=best.weights.h5
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: unless-stopped
